algoritmo "Exercício 7"
var
   co: inteiro
inicio
      escreva ("qual é o código de origem?")
      leia (co)
      escolha co
         caso 1
            escreva ("procedência: norte")
         caso 2
            escreva ("procedência: sul")
         caso 3
            escreva ("procedência: nordeste")
         caso 4, 5, 6
            escreva ("procedência: sudeste")
         caso 7, 8, 9, 10
            escreva ("procedência: centro-oeste")
      fimescolha
fimalgoritmo